base_path: .
base_url: https://api.crowdin.com
preserve_hierarchy: true
pull_request_labels:
  - crowdin
  - l10n
files:
  - source: /Jellyfin.Plugin.Themerr/Locale/en.json
    dest: /themerr-jellyfin.json
    translation: /Jellyfin.Plugin.Themerr/Locale/%two_letters_code%.%file_extension%
    update_option: update_as_unapproved
